### ISSUE TITLE
토큰 발급 로직 리팩토링

### ISSUE THREAD

**Issue by eogus2513** [EntryDSM/Raise-Percent#166]
### Describe

JwtTokenProvider 리팩토링 해주세요

### Work

- [x] role를 String ->  Role.enum으로 수정
- [x] refresh저장 로직 추가(service)

**Comment by leeseojune53** [comment]
여기서 refresh저장로직 추가는 jwtTokenProvider 리팩토링에 들어가는건가? @eogus2513

**Comment by leeseojune53** [comment]
그리고 두 번쨰거는 expiration time이 달라서 그것도 같이 받아야함 ㅜㅜ

**Comment by eogus2513** [comment]
@leeseojune53 넵 첫번쨰 질문은 리팩토링에 들어가요
두번째꺼는 추가하겠습니다

**Comment by leeseojune53** [comment]
저장로직이 JwtTokenProvider에 들어간다는건가요??

**Comment by leeseojune53** [comment]
두 번째꺼는 만약 한다면 매개변수가 너무 많아질 것 같습니다. email, role, exptime, type ...

**Comment by eogus2513** [comment]
저장 로직은 service에 들어가야 되서 이슈 이름 바꿨습니다.
그리고 두 번째꺼는 만약 한다면 매개변수가 너무 많아질 것 같습니다. email, role, exptime, type ...이거는 빼도록 하겠습니다.
